### ISSUE TITLE
tranzakcio kezeles teszt forgatokony

### ISSUE THREAD

**Issue by kryzsu** [me-kry-student-task-checker/stc-main#20]
user last activity
kurzus kérés ami minden szerviznek megy, db állapot fagyasztás - statisztika
eureka statisztika ki elérhető akár részlegesen (függőségei nem elérhetők)

**Comment by szattila98** [comment]
User last activity, preferencia lekérdezéssel és mock notificationnel rendben lesz mint teszteset, 
db állapot fagyasztás egyelőre még kérdéses.
Eureka statisztika jegelve.
